pycon/finaid/urls.py
from django.conf.urls import url

from .views import finaid_edit, finaid_email, finaid_message, finaid_review, \
    finaid_review_detail, finaid_status, finaid_download_csv, \
    phyllis_finaid_download_csv, speaker_grant_edit, \
    receipt_upload, FinaidAcceptView, FinaidDeclineView, \
    FinaidProvideInfoView, FinaidWithdrawView, FinaidRequestMoreView


urlpatterns = [
    url(r"^apply/$", finaid_edit, name="finaid_apply"),
    url(r"^edit/$", finaid_edit, name="finaid_edit"),
    url(r"^speaker/apply/$", speaker_grant_edit, name="speaker_grant_apply"),
    url(r"^speaker/edit/$", speaker_grant_edit, name="speaker_grant_edit"),
    url(r'^provide_info/$', FinaidProvideInfoView.as_view(), name="finaid_provide_info"),
    url(r"^withdraw/$", FinaidWithdrawView.as_view(), name="finaid_withdraw"),
    url(r"^decline/$", FinaidDeclineView.as_view(), name="finaid_decline"),
    url(r"^accept/$", FinaidAcceptView.as_view(), name="finaid_accept"),
    url(r"^request_more/$", FinaidRequestMoreView.as_view(), name="finaid_request_more"),
    url(r"^review/$", finaid_review, name="finaid_review"),
    url(r"^review/(?P<pks>[0-9,]+)/$", finaid_review, name="finaid_review"),
    url(r"^review/details/(?P<pk>\d+)/$", finaid_review_detail,
        name="finaid_review_detail"),
    url(r"^status/$", finaid_status, name="finaid_status"),
    url(r"^mail/(?P<pks>[0-9,]+)/$", finaid_email, name="finaid_email"),
    url(r"^message/(?P<pks>[0-9,]+)/$", finaid_message, name="finaid_message"),
    url(r"^download/$", finaid_download_csv, name="finaid_download_csv"),
    url(r"^phyllis_download/$", phyllis_finaid_download_csv, name="phyllis_finaid_download_csv"),
    url(r"^receipt_upload/$", receipt_upload, name="receipt_upload"),

]

pycon/profile/urls.py
from django.conf.urls import *


urlpatterns = patterns("pycon.profile.views",
    url(r"^edit/$", "profile_edit", name="profile_edit"),
)

pycon/schedule/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns(
    "pycon.schedule.views",
    url(r"^sessions/staff.txt$", "session_staff_email", name="schedule_session_staff_email"),
    url(r"^sessions/$", "session_list", name="schedule_session_list"),
    url(r"^session/(\d+)/$", "session_detail", name="schedule_session_detail"),
    url(r"^session-staff.json", "session_staff_json", name="session_staff_json"),
)

pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
    url(r'^events/overview/$', views.scheduled_event_overview, name='scheduled_event_overview'),
    url(r'^event/(?P<slug>.*)/$', views.scheduled_event, name='scheduled_event'),
    url(r'startuprow/apply/$', views.startuprow_apply, name='startuprow_apply'),
    url(r'community/roomsharing/$', views.room_sharing, name='room_sharing'),
    url(r'community/roomsharing/offer/$', views.room_sharing_offer, name='room_sharing_offer'),
    url(r'community/roomsharing/request/$', views.room_sharing_request, name='room_sharing_request'),
    url(r'community/roomsharing/offer/withdraw/$', views.withdraw_room_sharing_offer, name='withdraw_room_sharing_offer'),
    url(r'community/roomsharing/request/withdraw/$', views.withdraw_room_sharing_request, name='withdraw_room_sharing_request'),
)

pycon/sponsorship/models.py
import datetime
from django.conf import settings

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import SET_NULL
from django.db.models.signals import post_init, post_save, pre_save
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.template import Context, Template

from django.contrib.auth.models import User
from multi_email_field.fields import MultiEmailField

from symposion.conference.models import Conference

from pycon.sponsorship import SPONSOR_COORDINATORS
from pycon.sponsorship.managers import SponsorManager
from symposion.utils.mail import send_email


# The benefits we track as individual fields on sponsors
# using separate SponsorBenefit records.
# Names are the names in the database as defined by PyCon organizers.
# Field names are the benefit names, lowercased, with
# spaces changed to _, and with "_benefit" appended.
# Column titles are arbitrary.

BENEFITS = [
    {
        'name': 'Print logo',
        'field_name': 'print_logo_benefit',
        'column_title': _(u'Print Logo'),
    },
    {
        'name': 'Advertisement',
        'field_name': 'advertisement_benefit',
        'column_title': _(u'Ad'),
    }
]


class SponsorLevel(models.Model):

    conference = models.ForeignKey(Conference, verbose_name=_("conference"))
    name = models.CharField(_("name"), max_length=100)
    available = models.BooleanField(default=True)
    display = models.BooleanField(default=True)
    order = models.IntegerField(_("order"), default=0)
    cost = models.PositiveIntegerField(_("cost"))
    description = models.TextField(_("description"), blank=True, help_text=_("This is private."))

    class Meta:
        ordering = ["conference", "order"]
        verbose_name = _("sponsor level")
        verbose_name_plural = _("sponsor levels")

    def __unicode__(self):
        return u"%s %s" % (self.conference, self.name)

    def sponsors(self):
        return self.sponsor_set.filter(active=True).order_by("added")


class SponsorPackage(models.Model):

    conference = models.ForeignKey(Conference, verbose_name=_("conference"))
    name = models.CharField(_("name"), max_length=100)
    available = models.BooleanField(default=True)
    display = models.BooleanField(default=True)
    order = models.IntegerField(_("order"), default=0)
    cost = models.PositiveIntegerField(_("cost"))
    description = models.TextField(_("description"), blank=True, help_text=_("This is private."))

    class Meta:
        ordering = ["conference", "order"]
        verbose_name = _("sponsor package")
        verbose_name_plural = _("sponsor packages")

    def __unicode__(self):
        return u"%s %s" % (self.conference, self.name)

    def sponsors(self):
        return self.sponsor_set.filter(active=True).order_by("added")


class Sponsor(models.Model):

    applicant = models.ForeignKey(User, related_name="sponsorships", verbose_name=_("applicant"), null=True, on_delete=SET_NULL)

    name = models.CharField(_("Sponsor Name"), max_length=100)
    display_url = models.CharField(
        _("Link text - text to display on link to sponsor webpage, if different from the actual link"),
        max_length=200,
        default='',
        blank=True
    )
    external_url = models.URLField(
        _("Link to sponsor webpage"),
        help_text=_("(Must include https:// or http://.)")
    )
    twitter_username = models.CharField(
        _("Twitter username"), blank=True, max_length=15,
    )
    annotation = models.TextField(_("annotation"), blank=True)
    contact_name = models.CharField(_("Contact Name"), max_length=100)
    contact_emails = MultiEmailField(
        _(u"Contact Emails"), default='',
        help_text=_(u"Please enter one email address per line.")
    )
    contact_phone = models.CharField(_(u"Contact Phone"), max_length=32)
    contact_address = models.TextField(_(u"Contact Address"))
    level = models.ForeignKey(SponsorLevel, verbose_name=_("level"))
    packages = models.ManyToManyField(SponsorPackage, verbose_name=_("packages"), blank=True)
    added = models.DateTimeField(_("added"), default=datetime.datetime.now)

    active = models.BooleanField(_("active"), default=False)
    approval_time = models.DateTimeField(null=True, blank=True, editable=False)

    wants_table = models.BooleanField(
        _(
            'Does your organization want a table at the job fair? '
            '(See <a href="/2019/sponsors/fees/">Estimated Sponsor Fees</a> '
            'for costs that might be involved.)'
        ), default=False)
    wants_booth = models.BooleanField(
        _(
            'Does your organization want a booth on the expo floor? '
            '(See <a href="/2019/sponsors/fees/">Estimated Sponsor Fees</a> '
            'for costs that might be involved.)'
        ), default=False)
    small_entity_discount = models.BooleanField(
        _(
            'Does your organization have fewer than 25 employees,'
            ' which qualifies you for our Small Entity Discount of 30%?'
        ), default=False)

    # Whether things are complete
    # True = complete, False = incomplate, Null = n/a for this sponsor level
    print_logo_benefit = models.NullBooleanField(help_text=_(u"Print logo benefit is complete"))
    advertisement_benefit = models.NullBooleanField(help_text=_(u"Advertisement benefit is complete"))

    registration_promo_codes = models.CharField(max_length=200, blank=True, default='')
    expo_promo_codes = models.CharField(max_length=200, blank=True, default='')
    additional_discounted_registration_promo_codes = models.CharField(max_length=200, blank=True, default='')
    a_la_carte_registration_promo_codes = models.CharField(max_length=200, blank=True, default='')
    booth_number = models.IntegerField(blank=True, null=True, default=None)
    job_fair_participant = models.BooleanField(default=False)
    job_fair_table_number = models.IntegerField(blank=True, null=True, default=None)

    web_description = models.TextField(
        _(u"Company description (to show on the web site)"),
    )
    web_logo = models.ImageField(
        _(u"Web logo"),
        help_text=_("For display on our sponsor webpage. High resolution PNG or JPG, smallest dimension no less than 256px"),
        upload_to="sponsor_files",
        null=True,  # This is nullable in case old data doesn't have a web logo
        # We enforce it on all new or edited sponsors though.
    )
    print_logo = models.FileField(
        _(u"Print logo"),
        help_text=_("For printed materials, signage, and projection. SVG or EPS"),
        upload_to="sponsor_files",
        blank=True,
        null=True,  # This is nullable in case old data doesn't have a printed logo
        # We enforce it on all new or edited sponsors though.
    )

    objects = SponsorManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("sponsor")
        verbose_name_plural = _("sponsors")
        ordering = ['name']

    def save(self, *args, **kwargs):
        # Set fields related to benefits being complete
        for benefit in BENEFITS:
            field_name = benefit['field_name']
            benefit_name = benefit['name']
            setattr(self, field_name, self.benefit_is_complete(benefit_name))
        super(Sponsor, self).save(*args, **kwargs)

    def get_absolute_url(self):
        if self.active:
            return reverse("sponsor_detail", kwargs={"pk": self.pk})
        return reverse("sponsor_list")

    def get_display_url(self):
        """
        Return the text to display on the sponsor's link
        """
        if self.display_url:
            return self.display_url
        else:
            return self.external_url

    def render_email(self, text):
        """Replace special strings in text with values from the sponsor.

        %%NAME%% --> Sponsor name
        %%REGISTRATION_PROMO_CODES%% --> Registration promo codes, or empty string
        %%EXPO_PROMO_CODES%% --> Expo Hall only promo codes, or empty string
        %%ADDITIONAL_DISCOUNTED_REGISTRATION_PROMO_CODES%% --> Additional Discounted Registration promo codes, or empty string
        %%A_LA_CARTE_REGISTRATION_PROMO_CODES%% --> A la Carte Registration promo codes, or empty string
        %%BOOTH_NUMBER%% --> Booth number, or empty string if not set
        %%JOB_FAIR_TABLE_NUMBER%%" --> Job fair table number, or empty string if not set

        Flags:
          JOB_FAIR_PARTICIPANT: Use with {% if JOB_FAIR_PARTICIPANT %} block to
                                include some content for Job Fair Participants
        """
        text = text.replace("%%NAME%%", self.name)
        text = text.replace("%%REGISTRATION_PROMO_CODES%%",
                            self.registration_promo_codes or 'N/A')
        text = text.replace("%%EXPO_PROMO_CODES%%",
                            self.expo_promo_codes or 'N/A')
        text = text.replace("%%ADDITIONAL_DISCOUNTED_REGISTRATION_PROMO_CODES%%",
                            self.additional_discounted_registration_promo_codes or 'N/A')
        text = text.replace("%%A_LA_CARTE_REGISTRATION_PROMO_CODES%%",
                            self.a_la_carte_registration_promo_codes or 'N/A')

        # The next two are numbers, or if not set, None.  We don't want to
        # display "None" :-), but we might want to display "0".
        booth = str(self.booth_number) if self.booth_number is not None else ""
        text = text.replace("%%BOOTH_NUMBER%%", booth)
        table = str(self.job_fair_table_number) if self.job_fair_table_number is not None else ""
        text = text.replace("%%JOB_FAIR_TABLE_NUMBER%%", table)
        email_template = Template(text)
        email_context = Context({
            'JOB_FAIR_PARTICIPANT': self.job_fair_participant,
        })

pycon/profile/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        
        self.fields.keyOrder = [
            "first_name",
            "last_name",
            "phone",
        ]

pycon/mentorship/views.py
import random

from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from pycon.mentorship.models import MentorshipSlot
from pycon.mentorship.models import MentorshipMentee
from pycon.mentorship.models import MentorshipSession
from pycon.mentorship.models import generate_availabile_slots


@login_required
def mentorship_view(request):
     timezone = request.user.account.timezone if request.user.account.timezone else 'US/Eastern'
     mentee, created = request.user.mentorship_mentee.get_or_create(user=request.user)
     if (not request.user.mentorship_mentee.get().eligible) or (len(request.user.mentorship_mentee.get().potential_sessions_as_mentee) > 0):
         return render(
             request, "mentorship/mentorship_signup_recieved.html",
             {
                 "potential_slots": request.user.mentorship_mentee.get().potential_sessions_as_mentee,
                 "assigned_slots": request.user.mentorship_mentee.get().assigned_sessions_as_mentee,
                 "timezone": timezone,
             }
         )
     # Short circuit out
     return render(request, "mentorship/mentorship_slots_full.html", {})
     if request.user.speaker_profile.interested_mentee != "":
         slots = generate_availabile_slots()
         if request.method == 'POST':

             errors = []
             selected_slots = []

             try:
                 selected_slots = [MentorshipSlot.objects.get(id=int(x)) for x in request.POST.getlist('slot_list')]
             except ObjectDoesNotExist:
                 errors.append(ValidationError(_("Invalid Slot selected"), 'invalid_slot'))

             if not all([s in slots for s in selected_slots]):
                 errors.append(ValidationError(_("Invalid Slot selected, it may have been scheduled already"), 'invalid_slot'))

             if len(selected_slots) > 3:
                 errors.append(ValidationError(_("Too many slots selected, limited to 3"), 'too_many_slots'))

             if errors:
                 return render(request, "mentorship/mentorship_slots_view.html", {"slots": slots, "timezone": timezone, "errors": errors})

             for slot in selected_slots:
                 session, created = MentorshipSession.objects.get_or_create(finalized=False, slot=slot)
                 for i in range(session.mentors.count(), 2):
                     mentors = slot.available_mentors()
                     session.mentors.add(mentors[random.randint(0, len(mentors)-1)])
                 mentee, created = MentorshipMentee.objects.get_or_create(user=request.user)
                 session.mentees.add(mentee)
                 session.save()
                 mentee.responded = True
                 mentee.save()

             return render(
                 request, "mentorship/mentorship_signup_recieved.html",
                 {
                     "potential_slots": request.user.mentorship_mentee.get().potential_sessions_as_mentee,
                     "assigned_slots": request.user.mentorship_mentee.get().assigned_sessions_as_mentee,
                     "timezone": timezone,
                 }
             )

         else:
             return render(request, "mentorship/mentorship_slots_view.html", {"slots": slots, "timezone": timezone})
     else:
         return Http404()

pycon/templates/_account_bar.html
{% load url from future %}
{% load account_tags %}
{% load i18n %}

<div class="account-nav-container">
    <div class="max-width-container">
        {% if user.is_authenticated %}
            {% if request.user.get_full_name%}
                <strong>{% user_display request.user %}</strong>
            {% endif %}
            {% if user.is_staff %}
                <a href="{% url 'admin:index' %}" class="action">{% trans "Admin" %}</a>
            {% endif %}
            <a href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a>
            <a href="{% url 'account_settings' %}">{% trans "Settings" %}</a>
            <form action="{% url 'account_logout' %}" method="post">{% csrf_token %}
                <button class="btn logout" type="submit">{% trans "Log Out" %}</button>
            </form>
        {% else %}
            <a class="login" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
            <a class="signup" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
        {% endif %}
    </div>
</div>

pycon/templates/_messages.html
{% if messages %}
<div class="messages">
  {% for message in messages %}
  <div class="message">
    <button>&times;</button>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

pycon/templates/_sponsorship_link.html
{% load i18n %}

<a href="{% url 'cms_page' "sponsors/prospectus/" %}">
	{% trans "Sponsorship available! Learn more" %} <i class="icon icon-arrow-right"></i>
</a>

pycon/templates/auth_base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body_class %}auth{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a></li>
    </ul>
{% endblock %}

{% block sidebar %}{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $(function() {
            // Prepend @ symbol to any twitter username fields
            var twitterInput = $("#id_twitter_username");
            if (twitterInput) {
                var wrapperdiv = $("<div class='input-prepend'/>");
                var twitterInput = $("#id_twitter_username");

                twitterInput.parent("div.controls").prepend(wrapperdiv);
                wrapperdiv.append("<span class='add-on'>@</span>", twitterInput);
            };
        });
    </script>
{% endblock %}

pycon/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load cache %}
{% load compress %}
{% load sponsorship_tags %}
{% load thumbnail %}
{% load boxes_tags %}
{% load biblion_tags %}
{% load staticfiles %}

{% block head_title_base %}{{ SITE_NAME }} in Cleveland, Ohio | May 1-9{% endblock %}

{% block body_class %}home-page{% endblock %}

{% block header-imagery %}
<div class="home-banner">
  <div class="home-banner-stripe">
    <div class="max-width-container">
      <h1>PyCon 2019 in Cleveland, Ohio, USA</h1>
      <div class="tagline-container">
        <h2>
          <span class="date">May 1 &ndash; 9</span>
          <span class="tag1">By the Community</span>
          <span class="tag2">For the Community</span>
        </h2>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block banner %}
{% box "homepage-about" %}

<div class="front-page-facets-blue-bg">
  <div class="front-page-facets max-width-container">
    <div>
      <img src="{% static "img/tutorial-photo.jpg" %}" alt="People working together at a tutorial" class="photo">
      <h3>Tutorials</h3>
      <h4>May 1-2 • Wednesday, Thursday</h4>
      <img src="{% static "img/yellow-squiggle.svg" %}" alt="" class="squiggle">
      <p>
        The first 2 days of the conference
        offer a schedule packed with 3-hour tutorials
        to help both beginners and experienced developers
        learn new technologies and increase their skills.
      </p>
    </div><div>
      <img src="{% static "img/talks-photo.jpg" %}" alt="A woman presenting" class="photo">
      <h3>Talks &amp; Events</h3>
      <h4>May 3–5 • Friday, Saturday, Sunday</h4>
      <img src="{% static "img/yellow-squiggle.svg" %}" alt="" class="squiggle">
      <p>
        The 3 main conference days offer almost 100 talks,
        an Expo Hall where you can visit our sponsors,
        and events including an academic poster session,
        a Job Fair, and an annual benefit auction.
      </p>
    </div>
    <div>
      <img src="{% static "img/sprints-photo.jpg" %}" alt="Developers working at a sprint" class="photo">
      <h3>Sprints</h3>
      <h4>May 6–9 • Monday through Thursday</h4>
      <img src="{% static "img/yellow-squiggle.svg" %}" alt="" class="squiggle">
      <p>
        The final 4 days are our developer sprints,
        where developers both veteran and novice
        enjoy several days of rare in-person collaboration
        on their favorite open source projects.
      </p>
    </div>
  </div>
</div>

<div class="front-page-facets-white-bg">
  <div class="front-page-facets narrow max-width-container">
    <h2>
      Coming Soon!
    </h2>
    <!--
    <div>
      <img src="{% static "img/PNG/tutorials-icon.png" %}" alt="">
      <h3>PyCon 2019 has concluded.</h3>
      <p>
      Thanks to everyone who attended, volunteered, spoke, taught a tutorial,
      ran an open space, sprinted, sponsored, and made PyCon 2019 a successful conference.
      </p>
    </div>
    <div>
      <img src="{% static "img/PNG/conference-icon.png" %}" alt="">
      <h3>Retrospect on the schedule</h3>
      <p><a href="/2019/schedule/talks/" class="btn danger">Talks</a></p>
      <p><a href="/2019/schedule/tutorials/" class="btn danger">Tutorials</a></p>
    </div> -->
    <div>
      <img src="{% static "img/SVG/sprints-icon.svg" %}" width="200" height="200" alt="">
      <h3>Our sponsors</h3>
      <p><a href="/2019/sponsors/apply/" class="btn">Apply to Sponsor!</a></p>
      <p>The companies and organizations who sponsor PyCon
      make the conference possible,
      and get to connect with a wide array of Python programmers.</p>
    </div>
  </div>
</div>

{% endblock %}

{% block body_outer %}


{# Sponsors #}

<!--
<h2>Sponsors</h2>

<p class="front-page-sponsors">
  {% sponsors as all_sponsors %}
  {% for sponsor in all_sponsors %}
  <a href="{{ sponsor.external_url }}" title="{{ sponsor.name }}">
    <img src="{{ sponsor.website_logo|thumbnail_url:'sponsor_homepage' }}" alt="">
  </a>
  {% endfor %}
</p>
-->

{% endblock %}

{% block credits %}
<p>
  Thanks to Mike Pirnat for the
  <a href="https://www.flickr.com/photos/mikepirnat/42481637624/"
     >talk photo</a>
  used above!
</p>
{% endblock %}

pycon/templates/room_sharing.html
{% extends "cms/page_detail.html" %}
{% load boxes_tags %}


{% block page_content %}

<div style="text-align: center">
  <h1>Room Sharing</h1>
</div>

<div class="row">
    {% box "room_sharing" %}
</div>

<hr>

<div style="text-align: center">
  <span><h2>Submit a Room Sharing offer or request</h2></span>
  {% if user.is_authenticated %}
    {% if user.room_sharing_offer %}
      <a href="{% url 'room_sharing_offer' %}" class="btn">Update or withdraw my Room Sharing Offer</a>
    {% elif user.room_sharing_request %}
      <a href="{% url 'room_sharing_request' %}" class="btn">Update or withdraw my Room Sharing Request</a>
    {% else %}
      <a href="{% url 'room_sharing_offer' %}" class="btn">I have a Room to share</a>
      <a href="{% url 'room_sharing_request' %}" class="btn">I'm looking for a Room</a>
    {% endif %}
  {% else %}
  <a href="{% url 'account_login' %}?next={% url 'room_sharing' %}" class="btn">Login to continue...</a>
  {% endif %}
</div>

<hr>

<div>
  <span><h2>Rooms Offered</h2></span>
  <div>
    <ul>
  {% for room_sharing_offer in room_sharing_offers %}
      <li>
          <p>
            Dates: {{ room_sharing_offer.arrive }} - {{ room_sharing_offer.depart }}<br>
            Contact Info: {{ room_sharing_offer.contact_info }}<br>
            Additional Info: {{ room_sharing_offer.additional_info }}
          </p>
      </li>
  {% endfor %}
    </ul>
  </div>
</div>

<hr>

<div>
  <span><h2>Rooms Needed</h2></span>
  <div>
    <ul>
  {% for room_sharing_request in room_sharing_requests %}
      <li>
          <p>
            Dates: {{ room_sharing_request.arrive }} - {{ room_sharing_request.depart }}<br>
            Contact Info: {{ room_sharing_request.contact_info }}<br>
            Additional Info: {{ room_sharing_request.additional_info }}
          </p>
      </li>
  {% endfor %}
    </ul>
  </div>
</div>

<hr>

<div style="text-align: center; font: smaller;">
See something inappropriate or fishy? Let us know at <a href="mailto:pycon-reg@python.org">pycon-reg@python.org</a>.
</div>

{% endblock page_content %}

pycon/templates/scheduled_event.html
{% extends "cms/page_detail.html" %}

{% block box %}
  <h2>{{ event.location }}</h2>
  <p>
    {% if event.start|date == event.end|date %}
      {{ event.start|date }}, {{ event.start|time }} &ndash; {{ event.end|time }}
    {% else %}
      {{ event.start|date }}, {{ event.start|time }} &ndash; {{ event.end|date }}, {{ event.end|time }}
    {% endif %}
  </p>
  {# class box-content will cause this to get rendered as markdown #}
  <div class="box-content">{{ event.description|safe }}</div>
{% endblock box %}

pycon/templates/scheduled_event_overview.html
{% extends "cms/page_detail.html" %}

{% block box %}

  {% regroup events by start|date:"Y-m-d" as events_by_day %}

  {% for day in events_by_day %}
    <h1>{{ day.grouper }}</h1>

    {% for event in day.list %}
    <h2>{{ event.name }}</h2>
    <h3>{{ event.location }}</h3>
    <p>
      {% if event.start|date == event.end|date %}
        {{ event.start|date }}, {{ event.start|time }} &ndash; {{ event.end|time }}
      {% else %}
        {{ event.start|date }}, {{ event.start|time }} &ndash; {{ event.end|date }}, {{ event.end|time }}
      {% endif %}
    </p>
    {% endfor %}

  {% endfor %}


{% endblock box %}