pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
    url(r'^events/overview/$', views.scheduled_event_overview, name='scheduled_event_overview'),
    url(r'^event/(?P<slug>.*)/$', views.scheduled_event, name='scheduled_event'),
    url(r'startuprow/apply/$', views.startuprow_apply, name='startuprow_apply'),
    url(r'community/roomsharing/$', views.room_sharing, name='room_sharing'),
    url(r'community/roomsharing/offer/$', views.room_sharing_offer, name='room_sharing_offer'),
    url(r'community/roomsharing/request/$', views.room_sharing_request, name='room_sharing_request'),
    url(r'community/roomsharing/offer/withdraw/$', views.withdraw_room_sharing_offer, name='withdraw_room_sharing_offer'),
    url(r'community/roomsharing/request/withdraw/$', views.withdraw_room_sharing_request, name='withdraw_room_sharing_request'),
)

symposion/boxes/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns("symposion.boxes.views",
    url(r"^([-\w]+)/edit/$", "box_edit", name="box_edit"),
)

symposion/cms/urls.py
from django.conf.urls import url, patterns

PAGE_RE = r"(([\w-]{1,})(/[\w-]{1,})*)/"

urlpatterns = patterns("symposion.cms.views",
    url(r"^files/$", "file_index", name="file_index"),
    url(r"^files/create/$", "file_create", name="file_create"),
    url(r"^files/(\d+)/([^/]+)$", "file_download", name="file_download"),
    url(r"^files/(\d+)/delete/$", "file_delete", name="file_delete"),
    url(r"^(?P<path>%s)_edit/$" % PAGE_RE, "page_edit", name="cms_page_edit"),
    url(r"^(?P<path>%s)$" % PAGE_RE, "page", name="cms_page"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX, permanent=False)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",

        url(r"^sponsors/charityauction/$", RedirectView.as_view(
            url="/%s/events/auction/" % URL_PREFIX,
            permanent=True,
        )),

        # url(r"^$", RedirectView.as_view(
        #     url="/%s/sponsors/why-sponsor/" % URL_PREFIX,
        #     permanent=False,
        # )),
        # The real home page, currently shadowed:
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r'^selectable/', include('selectable.urls')),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^mentorship/", include("pycon.mentorship.urls")),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "comps" in settings.INSTALLED_APPS:
    urlpatterns += patterns("", url(r"^", include("comps.urls")))

pycon/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from easy_thumbnails.signals import saved_file

from pycon import tasks

from symposion.proposals.kinds import register_proposal_model
from symposion.proposals.models import ProposalBase


def strip(text):
    return u' '.join(text.strip().split())


class PyConProposalCategory(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "PyCon proposal category"
        verbose_name_plural = "PyCon proposal categories"


class ThunderdomeGroup(models.Model):
    """A set of talk proposals, grouped together for consideration within
    thunderdome.
    """
    label = models.CharField(max_length=250)
    code = models.CharField(max_length=20, unique=True)
    decided = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def as_dict(self):
        return {
            'code': self.code,
            'decided': self.decided,
            'label': self.label,
            'talks': [i.as_dict() for i in self.talks.order_by('id')],
        }


class PyConProposal(ProposalBase):
    # ABSTRACT MODEL
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, _(u"Novice")),
        (AUDIENCE_LEVEL_INTERMEDIATE, _(u"Intermediate")),
        (AUDIENCE_LEVEL_EXPERIENCED, _(u"Experienced")),
    ]

    STATUS_UNREVIEWED = 1
    STATUS_KITTENDOME = 2
    STATUS_THUNDERDOME = 3
    STATUS_ACCEPTED = 4
    STATUS_DAMAGED = 5
    STATUS_REJECTED = 6

    STATUS_OPTIONS = [
        (STATUS_UNREVIEWED, 'Not Yet Reviewed'),
        (STATUS_KITTENDOME, 'In Kittendome'),
        (STATUS_THUNDERDOME, 'In Thunderdome'),
        (STATUS_ACCEPTED, 'Accepted'),
        (STATUS_DAMAGED, 'Damaged'),
        (STATUS_REJECTED, 'Rejected'),
    ]

    REJECTION_POSTER = 1
    REJECTION_LIGHTNING = 2
    REJECTION_MOVED = 3
    REJECTION_DUPLICATE = 4
    REJECTION_ADMIN = 5
    REJECTION_BAD = 6

    REJECTION_OPTIONS = [
        (REJECTION_POSTER, 'Suggest re-submission as poster.'),
        (REJECTION_LIGHTNING, 'Suggest lightning talk.'),
        (REJECTION_MOVED, 'Re-submitted under appropriate category.'),
        (REJECTION_DUPLICATE, 'Duplicate'),
        (REJECTION_ADMIN, 'Administrative Action (Other)'),
        (REJECTION_BAD, "No really: rejected. It's just plain bad."),
    ]

    category = models.ForeignKey(PyConProposalCategory,
                                 blank=True, null=True)
    audience_level = models.IntegerField(
        choices=AUDIENCE_LEVELS,
        help_text=_(u'Level of audience expertise assumed in Python.'),
        verbose_name=_(u'Python level'))
    overall_status = models.IntegerField(
        choices=STATUS_OPTIONS,
        default=STATUS_UNREVIEWED,
        help_text=_(u'The status of the proposal.'))
    damaged_score = models.IntegerField(
        blank=True,
        null=True,
        help_text=_(u"Numerical indicator of the amount of interest in a talk set "
                    u"to 'damaged' status."))
    rejection_status = models.IntegerField(
        blank=True,
        null=True,
        choices=REJECTION_OPTIONS,
        help_text=_(u'The reason the proposal was rejected.'))
    recording_release = models.BooleanField(
        default=True,
        help_text=_(u"By submitting your proposal, you agree to give permission to "
                    u"the Python Software Foundation to record, edit, and release audio "
                    u"and/or video of your presentation. If you do not agree to this, "
                    u"please uncheck this box. See "
                    u"<a href='/2019/speaking/recording/' "
                    u"target='_blank'>PyCon 2019 Recording Release</a> for details.")
    )

    additional_requirements = models.TextField(
        _(u"Additional requirements"),
        blank=True,
        help_text=_(u"Please let us know if you have any specific needs (A/V requirements, "
                    u"multiple microphones, a table, etc).  Note for example that 'audio out' "
                    u"is not provided for your computer unless you tell us in advance.")
    )

    class Meta:
        abstract = True


class PyConTalkProposal(PyConProposal):

    DURATION_CHOICES = [
        (0, _(u"No preference")),
        (1, _(u"I prefer a 30 minute slot")),
        (2, _(u"I prefer a 45 minute slot")),
    ]

    duration = models.IntegerField(
        choices=DURATION_CHOICES,
        default=1,
        help_text=strip(
            u"""
            <i>Committee note:</i>
            There are far fewer 45 minute slots available
            than 30 minute slots,
            so not every accepted talk that requests a longer slot
            may be able to get it.
            If you select a 45 minute slot,
            please indicate in your outline (below)
            what content could be cut — if possible — for a 30 minute version.
            """
        ),
    )

    outline = models.TextField(
        help_text=strip(
            u"""
            The “outline” is a skeleton of your talk that is as detailed as
            possible, including rough timings or estimates for different
            sections. If requesting a 45 minute slot, please describe what
            content would appear in the 45 minute version but not a 30 minute
            version, either within the outline or in a paragraph at the
            end.<br>
            <br>
            <i>Committee note:</i> The outline is extremely important for the
            program committee to understand what the content and structure of
            your talk will be. The timings/percentages help us compare multiple
            talks that might have a similar abstract. We know that they are
            estimates and only capture your view at this moment in time and are
            likely to change before PyCon. We hope that writing the outline is
            helpful to you as well, to organize and clarify your thoughts for
            your talk! The outline will not be shared with conference
            attendees.<br>
            <br>
            If there’s too much to your topic to cover even in 45 minutes, you
            may wish to narrow it down. Alternatively, consider submitting a
            3-hour PyCon tutorial instead. If you plan to do live coding during
            your talk, please describe your backup plan in case the live coding
            fails (for whatever reason). Suggestions include a pre-recorded
            video, or slides to replace the live coding.
            """
        ),
    )
    audience = models.TextField(
        u"Who and Why (Audience)",
        help_text=strip(
            u"""
            1–2 paragraphs that should answer three questions:
            (1) Who is this talk for?
            (2) What background knowledge or experience
            do you expect the audience to have?
            (3) What do you expect the audience to learn or do
            after watching the talk?<br>
            <br>
            <i>Committee note:</i> The “Audience” section
            helps the program committee get a sense
            of whether your talk is geared more at novices
            or experienced individuals in a given subject.
            (We need a balance of both lower-level and advanced talks
            to make a great PyCon!)
            It also helps us evaluate the relevance of your talk
            to the Python community.
            """
        ),
    )

    # TODO: this does not actually remove the fields, so the form cannot
    # yet be submitted successfully.  Should we upgrade to Django 1.10?
    # abstract = None
    # additional_requirements = None
    # audience_level = None
    # category = None
    # perceived_value = None

    class Meta:
        verbose_name = "PyCon talk proposal"

    def as_dict(self, details=False):
        answer = super(PyConTalkProposal, self).as_dict(details=details)
        if details:
            answer['duration'] = self.get_duration_display()
            answer['outline'] = self.outline
            answer['audience'] = self.audience
            answer['recording_release'] = self.recording_release
        return answer


register_proposal_model('talk', PyConTalkProposal, 'Talks')

class PyConCharlaProposal(PyConTalkProposal):

    class Meta:
        verbose_name = "PyCon Charlas proposal"

register_proposal_model('charla', PyConCharlaProposal, 'Charlas')


class PyConLightningTalkProposal(PyConProposal):

    class Meta:
        verbose_name = "PyCon lightning talk proposal"


register_proposal_model('lightning-talk', PyConLightningTalkProposal, 'Lightning Talks')


class PyConTutorialProposal(PyConProposal):
    DOMAIN_LEVEL_NOVICE = 1
    DOMAIN_LEVEL_EXPERIENCED = 2
    DOMAIN_LEVEL_INTERMEDIATE = 3

    DOMAIN_LEVELS = [
        (DOMAIN_LEVEL_NOVICE, _(u"Novice")),
        (DOMAIN_LEVEL_INTERMEDIATE, _(u"Intermediate")),
        (DOMAIN_LEVEL_EXPERIENCED, _(u"Experienced")),
    ]

    domain_level = models.IntegerField(
        choices=DOMAIN_LEVELS,
        help_text=_(u'Level of audience expertise assumed in the '
                    u'presentation\'s domain.'))

    audience = models.TextField(
        u"Audience",
        help_text=strip(
            u"""
            1–2 paragraphs that should answer three questions:
            (1) Who is this tutorial for?
            (2) What background knowledge or experience
            do you expect students to have?

symposion/boxes/forms.py
from django import forms

from markedit.widgets import MarkEdit

from symposion.boxes.models import Box


class BoxForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ["content"]
        widgets = {
            "content": MarkEdit(),
        }

symposion/cms/forms.py
from django import forms
from django.conf import settings

from markedit.widgets import MarkEdit

from .models import Page


class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ["title", "body", "body_fr", "path"]
        widgets = {
            "path": forms.HiddenInput(),
            "body": MarkEdit(),
            "body_fr": MarkEdit(),
        }
        if not settings.USE_I18N:
            fields.remove('body_fr')
            del widgets['body_fr']


class FileUploadForm(forms.Form):

    file = forms.FileField()

symposion/boxes/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from symposion.boxes.authorization import load_can_edit
from symposion.boxes.forms import BoxForm
from symposion.boxes.models import Box


# @@@ problem with this is that the box_edit.html and box_create.html won't have domain objects in context
def get_auth_vars(request):
    auth_vars = {}
    if request.method == "POST":
        keys = [k for k in request.POST.keys() if k.startswith("boxes_auth_")]
        for key in keys:
            auth_vars[key.replace("boxes_auth_", "")] = request.POST.get(key)
        auth_vars["user"] = request.user
    return auth_vars


@require_POST
def box_edit(request, label):
    
    if not load_can_edit()(request, **get_auth_vars(request)):
        return HttpResponseForbidden()
    
    next = request.GET.get("next")
    
    try:
        box = Box.objects.get(label=label)
    except Box.DoesNotExist:
        box = None
    
    form = BoxForm(request.POST, instance=box, prefix=label)

    if form.is_valid():
        if box is None:
            box = form.save(commit=False)
            box.label = label
            box.created_by = request.user
            box.last_updated_by = request.user
            box.save()
        else:
            form.save()
        return redirect(next)

symposion/conference/views.py
from django.http import Http404
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


@login_required
def user_list(request):
    
    if not request.user.is_staff:
        raise Http404()
    
    return render(request, "conference/user_list.html", {
        "users": User.objects.all(),
    })

symposion/templates/reviews/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
    <li><code>{% templatetag openvariable %} proposal.speakers {% templatetag closevariable %}</code> e.g. {% for speaker in proposals.0.speakers %}{{ speaker.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
</ul>

symposion/templates/reviews/_review_table.html
{% load i18n %}

<table class="table table-striped table-bordered table-reviews">
    <thead>
        <th>#</th>
        <th>{% trans "Speaker" %}</th>
        <th>{% trans "Title" %}</th>
        <th>{% trans "Category" %}</th>
        <th>{% trans "Tags" %}</th>
        {% if section_slug == "talks" %}
            <th>{% trans "Review Start" %}</th>
        {% endif %}
        <th>Total Votes</th>
        {% if section_slug == "talks" %}
            <th>{% trans "Voting Start" %}</th>
        {% endif %}
        <th>{% trans "Your Vote" %}</th>
        <th>+1</th>
        <th>+0</th>
        <th>-0</th>
        <th>-1</th>
        <th>{% trans "Overall Status" %}</th>
        {% if can_manage %}
            <th>{% trans "Update Overall Status" %}</th>
        {% endif %}
        {% if request.user.is_superuser %}
            <th>{% trans "Rejection Status" %}</th>
        {% endif %}
    </thead>

    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }}">
                <td>{{ proposal.number }}</td>
                <td>
                    {{ proposal.speaker }}
                    <br />
                    &lt;{{ proposal.speaker.email }}&gt;
                </td>
                <td>
                    {% if proposal.cancelled %}
                        <strike>
                    {% endif %}
                    <a href="{% url 'review_detail' proposal.pk %}">
                        {{ proposal.title }}
                    </a>
                    {% if proposal.cancelled %}
                        </strike>
                    {% endif %}
                </td>
                <td>{{ proposal.category }}</td>
                <td>{{ proposal.cached_tags }}</td>
                {% if section_slug == "talks" %}
                    <td>{{ proposal.result.group.review_start|date:"M. j H:i T" }}</td>
                {% endif %}
                <td>{{ proposal.comment_count }}</td>
                {% if section_slug == "talks" %}
                    <td>{{ proposal.result.group.vote_start|date:"M. j H:i T" }}</td>
                {% endif %}
                <td>
                {% if proposal.user_vote %}
                    <b>{{ proposal.user_vote }}</b>
                {% endif %}
                </td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.plus_zero }}</td>
                <td>{{ proposal.minus_zero }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>
                    {% if proposal.cancelled %}
                        <i>Cancelled</i>
                    {% else %}
                        {{ proposal.get_overall_status_display }}
                    {% endif %}
                </td>
                {% if can_manage %}
                    <td>
                      {% if proposal.cancelled %}
                          <i>Cancelled</i>
                      {% else %}
                        <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="pk" value="{{ proposal.pk }}" />
                                <select name="status" onChange="this.form.submit();">
                                    {% for k, v in status_options %}
                                    <option value="{{ k }}" {% if proposal.overall_status == k %}selected="selected"{% endif %}>
                                        {{ v }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </form>
                      {% endif %}
                    </td>
                {% endif %}
                {% if request.user.is_superuser %}
                    <td>
                        {% with proposal.get_rejection_status_display as status %}
                            {% if status %}
                                {{ status }}
                            {% else %}
                                N/A
                            {% endif %}
                        {% endwith %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

<!-- To change the status of multiple proposals at the same time -->
<form action="" method="POST">
  {% csrf_token %}
  <button id="button" type="submit" class="btn btn-primary">
    <i class="icon-check"></i>
    Change status of selected rows to
  </button>

<!-- We use jQuery below to change the value of this input to the selected rows -->
  <input id="multiInput" type="hidden" name="pks" value="" />
  <select name="status">
    {% for k, v in status_options %}
      <option value="{{ k }}" {% if proposal.overall_status == k %}selected="selected"{% endif %}>
        {{ v }}
      </option>
    {% endfor %}
  </select>
</form>

<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"
        type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"
        type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"
        type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"
        type="text/javascript"></script>

<script type="text/javascript">
    $(function() {
        $(".tip").tooltip();
        var table = $("table.table-reviews").DataTable({
            dom: 'Blfrtip',
            buttons: ['copy', 'csv', 'print'],
            lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]],
            pageLength: -1
        });
        // When a row is clicked it becomes selected
        $('table tbody').on( 'click', 'tr', function (event) {
            if ($(event.target).is('a')) return;
            $(this).toggleClass('selected');
        });

        // When the submit button is clicked all the selected rows are found and are sent as the value of multiInput
        $('#button').click( function () {
            var new_list=[];
            for (i=0; i<table.rows('.selected').data().length; i++){
              pk = table.rows('.selected').data()[i][0];
              new_list.push(pk);
            };
            $( "#multiInput" ).val( new_list );
    } );

    });
</script>

symposion/templates/reviews/access_not_permitted.html
{% extends "reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>
    
    <p>
        Sorry, you do not have permission to access this page. If you 
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

symposion/templates/reviews/base.html
{% extends "site_base.html" %}

{% load i18n %}
{% load sitetree %}

{% block extra_style %}
    <style type="text/css">
        div.dataTables_length label {
            float: left;
            text-align: left;
        }

        div.dataTables_length select {
            width: 75px;
        }

        div.dataTables_filter label {
            float: right;
        }

        div.dataTables_info {
            padding-top: 8px;
        }

        div.dataTables_paginate {
            float: right;
            margin: 0;
        }

        table.table {
            clear: both;
            margin-bottom: 6px !important;
            background-color: white;
        }

        tr.selected {
            background-color: grey;
        }

        .table-striped tbody > tr:nth-child(odd).selected > td {
            background-color: transparent;
        }

        .table-striped tbody > tr:nth-child(odd).selected > th {
            background-color: transparent;
        }

        table.table thead .sorting,
        table.table thead .sorting_asc,
        table.table thead .sorting_desc,
        table.table thead .sorting_asc_disabled,
        table.table thead .sorting_desc_disabled {
            cursor: pointer;
            *cursor: hand;
        }

        {% comment %}
        table.table thead .sorting { background: url('{{ STATIC_URL }}datatables/images/sort_both.png') no-repeat center right; }
        table.table thead .sorting_asc { background: url('{{ STATIC_URL }}datatables/images/sort_asc.png') no-repeat center right; }
        table.table thead .sorting_desc { background: url('{{ STATIC_URL }}datatables/images/sort_desc.png') no-repeat center right; }

        table.table thead .sorting_asc_disabled { background: url('{{ STATIC_URL }}datatables/images/sort_asc_disabled.png') no-repeat center right; }
        table.table thead .sorting_desc_disabled { background: url('{{ STATIC_URL }}datatables/images/sort_desc_disabled.png') no-repeat center right; }
        {% endcomment %}

        table.dataTable th:active {
            outline: none;
        }
    </style>
{% endblock %}

{% block body_class %}reviews{% endblock %}
{% block content_class %}reviews-content{% endblock %}

{% block body_outer %}
  {% include "_messages.html" %}

  {% block breadcrumbs %}
    {% sitetree_breadcrumbs from "main" %}
  {% endblock %}

  <p>
    {% for section in review_sections %}
      {{ section }}:
      <a href="{% url 'review_section' section.section.slug %}">
        {% trans "Reviews" %}
      </a>
      {% comment %}
      •
      <a href="{% url 'review_section_assignments' section.section.slug %}">
        {% trans "Your Assignments" %}
      </a>
      {% endcomment %}
      •
      <a href="{% url 'review_status' section.section.slug %}">
        {% trans "Voting Status" %}
      </a>
      {% if request.user.is_staff %}
      •
      <a href="{% url 'result_notification' section.section.slug 'accepted' %}">{% trans "Result Notification" %}</a>
      {% endif %}
      <br>
    {% endfor %}
  </p>

  {% block body %}
  {% endblock %}
{% endblock %}

symposion/templates/reviews/review_review.html
{% extends "site_base.html" %}

{% load uni_form_tags %}
{% load review_tags %}

{% block body_class %}review{% endblock %}

{% block body %}
    <h1>Proposal Review</h1>

    <div class="proposal">
        <h2>{{ proposal.title }}</h2>

        <p>
            {% if proposal.cancelled %}
                Cancelled
            {% endif %}
        </p>

        <div>
            {{ proposal.description }}
        </div>

        <p><b>Type</b>: {{ proposal.get_session_type_display }}</p>

        <h3>Abstract</h3>
        <div class="abstract">
            {{ proposal.abstract_html|bleach|safe }}
        </div>

        <p><b>Audience level</b>: {{ proposal.get_audience_level_display }}</p>

        <p><b>Submitting speaker</b>: {{ proposal.speaker }}</p> {# @@@ bio? #}

        {% if proposal.additional_speakers.all %}
            <p><b>Additional speakers</b>:</p>
            <ul>
            {% for speaker in proposal.additional_speakers.all %}
                {% if speaker.user %}
                    <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                {% else %}
                    <li>{{ speaker.email }} &mdash; pending invitation</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}

        <h3>Additional Notes (private from submitter)</h3>
        <div class="additional_notes">
            {{ proposal.additional_notes }}
        </div>
    </div>

    <h2>Review</h2>
    <form method="POST" action="{% url 'review_review' proposal.pk %}" class="uniForm">
        {% csrf_token %}
        <fieldset class="inlineLabels">
            {{ review_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>

    <h2>Comment</h2>
    <form method="POST" action="{% url 'review_comment' proposal.pk %}" class="uniForm">
        {% csrf_token %}
        <fieldset>
            {{ comment_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>

{% endblock %}